import = ["~/PDE/config/alacritty/jetbrains-mono.toml","~/PDE/config/alacritty/tokyo-night.toml"]

[env]
TERM = "xterm-256color"
LC_CTYPE = "en_US.UTF-8"

[shell]
program = "fish"

[window]
decorations = "full"
dynamic_padding = false
opacity = 1.0
padding.x = 4
padding.y = 2

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
